Citizen.CreateThread(function()
    while true do
-- Melee
        SetWeaponDamageModifier(`weapon_unarmed`, 1.0) -- Weapon Label (Fists)	
        SetWeaponDamageModifier(`weapon_dagger`, 1.0) -- Weapon Label (Dagger)	
        SetWeaponDamageModifier(`weapon_bat`, 1.0) -- Weapon Label (Bat)	
        SetWeaponDamageModifier(`weapon_bottle`, 1.0) -- Weapon Label (Broken Bottle)	
        SetWeaponDamageModifier(`weapon_crowbar`, 1.0) -- Weapon Label (Crowbar)	
        SetWeaponDamageModifier(`weapon_flashlight`, 1.0) -- Weapon Label (Flashlight)	
        SetWeaponDamageModifier(`weapon_golfclub`, 1.0) -- Weapon Label (Golfclub)	
        SetWeaponDamageModifier(`weapon_hammer`, 1.0) -- Weapon Label (Hammer)	
        SetWeaponDamageModifier(`weapon_hatchet`, 1.0) -- Weapon Label (Hatchet)	
        SetWeaponDamageModifier(`weapon_knuckle`, 1.0) -- Weapon Label (Knuckle)	
        SetWeaponDamageModifier(`weapon_knife`, 1.0) -- Weapon Label (Knife)	
        SetWeaponDamageModifier(`weapon_machete`, 1.0) -- Weapon Label (Machete)	
        SetWeaponDamageModifier(`weapon_switchblade`, 1.0) -- Weapon Label (Switchblade)	
        SetWeaponDamageModifier(`weapon_nightstick`, 1.0) -- Weapon Label (Nightstick)	
        SetWeaponDamageModifier(`weapon_wrench`, 1.0) -- Weapon Label (Wrench)	
        SetWeaponDamageModifier(`weapon_battleaxe`, 1.0) -- Weapon Label (Battle Axe)	
        SetWeaponDamageModifier(`weapon_poolcue`, 1.0) -- Weapon Label (Poolcue)
        SetWeaponDamageModifier(`weapon_stone_hatchet`, 1.0) -- Weapon Label (Stone Hatchet)	
-- Pistols
        SetWeaponDamageModifier(`weapon_pistol`, 1.0) -- Weapon Label (Walther P99)	
        SetWeaponDamageModifier(`weapon_combatpistol`, 1.0) -- Weapon Label (Combat Pistol)	
        SetWeaponDamageModifier(`weapon_appistol`, 1.0) -- Weapon Label (AP Pistol)	
        SetWeaponDamageModifier(`weapon_stungun`, 1.0) -- Weapon Label (Taser)	
        SetWeaponDamageModifier(`weapon_pistol50`, 1.0) -- Weapon Label (Pistol .50)	
        SetWeaponDamageModifier(`weapon_snspistol`, 1.0) -- Weapon Label (SNS Pistol)	
        SetWeaponDamageModifier(`weapon_heavypistol`, 1.0) -- Weapon Label (Heavy Pistol)	
        SetWeaponDamageModifier(`weapon_vintagepistol`, 1.0) -- Weapon Label (Vintage Pistol)	
        SetWeaponDamageModifier(`weapon_flaregun`, 1.0) -- Weapon Label (Flare Gun)	
        SetWeaponDamageModifier(`weapon_marksmanpistol`, 1.0) -- Weapon Label (Marksman Pistol)	
        SetWeaponDamageModifier(`weapon_revolver`, 1.0) -- Weapon Label (Revolver)	
        SetWeaponDamageModifier(`weapon_doubleaction`, 1.0) -- Weapon Label (Double Action Revolver)	
        SetWeaponDamageModifier(`weapon_raypistol`, 1.0) -- Weapon Label (Up-n-Atomizer)	
        SetWeaponDamageModifier(`weapon_ceramicpistol`, 1.0) -- Weapon Label (Ceramic Pistol)	
        SetWeaponDamageModifier(`weapon_navyrevolver`, 1.0) -- Weapon Label (Navy Revolver)	
        SetWeaponDamageModifier(`weapon_gadgetpistol`, 1.0) -- Weapon Label (Perico Pistol)	
-- MK2 Pistols
        SetWeaponDamageModifier(`weapon_pistol_mk2`, 1.0) -- Weapon Label (Pistol Mk II)	
        SetWeaponDamageModifier(`weapon_revolver_mk2`, 1.0) -- Weapon Label (Violence)	
        SetWeaponDamageModifier(`weapon_snspistol_mk2`, 1.0) -- Weapon Label (SNS Pistol Mk II)	
-- SMGS
        SetWeaponDamageModifier(`weapon_microsmg`, 1.0) -- Weapon Label (Micro SMG)
        SetWeaponDamageModifier(`weapon_smg`, 1.0) -- Weapon Label (SMG)
        SetWeaponDamageModifier(`weapon_assaultsmg`, 1.0) -- Weapon Label (Assault SMG)
        SetWeaponDamageModifier(`weapon_combatpdw`, 1.0) -- Weapon Label (Combat PDW)
        SetWeaponDamageModifier(`weapon_machinepistol`, 1.0) -- Weapon Label (Machine Pistol)
        SetWeaponDamageModifier(`weapon_minismg`, 1.0) -- Weapon Label (Mini SMG)
        SetWeaponDamageModifier(`weapon_raycarbine`, 1.0) -- Weapon Label (Unholy Hellbringer)
-- MK2 SMG
        SetWeaponDamageModifier(`weapon_smg_mk2`, 1.0) -- Weapon Label (SMG Mk II)
        --
-- Shotgun   
        SetWeaponDamageModifier(`weapon_pumpshotgun`, 1.0) -- Weapon Label (Pump Shotgun)
        SetWeaponDamageModifier(`weapon_sawnoffshotgun`, 1.0) -- Weapon Label (Sawn-off Shotgun)
        SetWeaponDamageModifier(`weapon_assaultshotgun`, 1.0) -- Weapon Label (Assault Shotgun)
        SetWeaponDamageModifier(`weapon_bullpupshotgun`, 1.0) -- Weapon Label (Bullpup Shotgun)
        SetWeaponDamageModifier(`weapon_musket`, 1.0) -- Weapon Label (Musket)
        SetWeaponDamageModifier(`weapon_heavyshotgun`, 1.0) -- Weapon Label (Heavy Shotgun)
        SetWeaponDamageModifier(`weapon_dbshotgun`, 1.0) -- Weapon Label (Double-barrel Shotgun)
        SetWeaponDamageModifier(`weapon_autoshotgun`, 1.0) -- Weapon Label (Auto Shotgun)
        SetWeaponDamageModifier(`weapon_combatshotgun`, 1.0) -- Weapon Label (Combat Shotgun)
-- MK2 Shotgun
        SetWeaponDamageModifier(`weapon_pumpshotgun_mk2`, 1.0) -- Weapon Label (Pumpshotgun Mk II)
-- Rifles
        SetWeaponDamageModifier(`weapon_assaultrifle`, 1.0) -- Weapon Label (Assault Rifle)
        SetWeaponDamageModifier(`weapon_carbinerifle`, 1.0) -- Weapon Label (Carbine Rifle)
        SetWeaponDamageModifier(`weapon_advancedrifle`, 1.0) -- Weapon Label (Advanced Rifle)
        SetWeaponDamageModifier(`weapon_specialcarbine`, 1.0) -- Weapon Label (Special Carbine)
        SetWeaponDamageModifier(`weapon_bullpuprifle`, 1.0) -- Weapon Label (Bullpup Rifle)
        SetWeaponDamageModifier(`weapon_compactrifle`, 1.0) -- Weapon Label (Compact Rifle)
        SetWeaponDamageModifier(`weapon_militaryrifle`, 1.0) -- Weapon Label (Military Rifle)
-- MK2 Rifles
        SetWeaponDamageModifier(`weapon_assaultrifle_mk2`, 1.0) -- Weapon Label (Assault Rifle Mk II)
        SetWeaponDamageModifier(`weapon_carbinerifle_mk2`, 1.0) -- Weapon Label (Carbine Rifle Mk II)
        SetWeaponDamageModifier(`weapon_specialcarbine_mk2`, 1.0) -- Weapon Label (Special Carbine Mk II)
        SetWeaponDamageModifier(`weapon_bullpuprifle_mk2`, 1.0) -- Weapon Label (Bullpup Rifle Mk II)
-- LMG
        SetWeaponDamageModifier(`weapon_mg`, 1.0) -- Weapon Label (Machinegun)
        SetWeaponDamageModifier(`weapon_combatmg`, 1.0) -- Weapon Label (Combat MG)
        SetWeaponDamageModifier(`weapon_gusenberg`, 1.0) -- Weapon Label (Thompson SMG)
-- MK2 LMG
        SetWeaponDamageModifier(`weapon_combatmg_mk2`, 1.0) -- Weapon Label (Combat MG Mk II)
-- Snipers
        SetWeaponDamageModifier(`weapon_sniperrifle`, 1.0) -- Weapon Label (Sniper Rifle)
        SetWeaponDamageModifier(`weapon_heavysniper`, 1.0) -- Weapon Label (Heavy Sniper)
        SetWeaponDamageModifier(`weapon_marksmanrifle`, 1.0) -- Weapon Label (Marksman Rifle)
        SetWeaponDamageModifier(`weapon_remotesniper`, 1.0) -- Weapon Label (Remote Sniper)
-- MK2 Snipers
        SetWeaponDamageModifier(`weapon_heavysniper_mk2`, 1.0) -- Weapon Label (Heavy Sniper Mk II)
        SetWeaponDamageModifier(`weapon_marksmanrifle_mk2`, 1.0) -- Weapon Label (Marksman Rifle Mk II)
-- Throwables
        SetWeaponDamageModifier(`weapon_grenade`, 1.0) -- Weapon Label (Grenade)
        SetWeaponDamageModifier(`weapon_bzgas`, 1.0) -- Weapon Label (BZ Gas)
        SetWeaponDamageModifier(`weapon_molotov`, 1.0) -- Weapon Label (Molotov)
        SetWeaponDamageModifier(`weapon_stickybomb`, 1.0) -- Weapon Label (C4)
        SetWeaponDamageModifier(`weapon_proxmine`, 1.0) -- Weapon Label (Proxmine Grenade)
        SetWeaponDamageModifier(`weapon_snowball`, 1.0) -- Weapon Label (Snowball)
        SetWeaponDamageModifier(`weapon_pipebomb`, 1.0) -- Weapon Label (Pipe Bomb)
        SetWeaponDamageModifier(`weapon_ball`, 1.0) -- Weapon Label (Ball)
        SetWeaponDamageModifier(`weapon_smokegrenade`, 1.0) -- Weapon Label (Smoke Grenade)
        SetWeaponDamageModifier(`weapon_flare`, 1.0) -- Weapon Label (Flare)
-- Heavy Weapons
        SetWeaponDamageModifier(`weapon_rpg`, 1.0) -- Weapon Label (RPG)
        SetWeaponDamageModifier(`weapon_grenadelauncher`, 1.0) -- Weapon Label (Grenade Launcher)
        SetWeaponDamageModifier(`weapon_grenadelauncher_smoke`, 1.0) -- Weapon Label (Smoke Grenade Launcher)
        SetWeaponDamageModifier(`weapon_minigun`, 1.0) -- Weapon Label (Minigun)
        SetWeaponDamageModifier(`weapon_firework`, 1.0) -- Weapon Label (Firework Launcher)
        SetWeaponDamageModifier(`weapon_railgun`, 1.0) -- Weapon Label (Railgun)
        SetWeaponDamageModifier(`weapon_hominglauncher`, 1.0) -- Weapon Label (Homing Launcher)
        SetWeaponDamageModifier(`weapon_compactlauncher`, 1.0) -- Weapon Label (Compact Launcher)
        SetWeaponDamageModifier(`weapon_rayminigun`, 1.0) -- Weapon Label (Widowmaker)
	Wait(1)
    end
end)

Citizen.CreateThread(function()
   while true do
       Wait(5)
       SetPedSuffersCriticalHits(PlayerPedId(), true) -- If Set To False Players Cant Take Critical Hits
    end
end)